

from os import listdir
from os.path import isfile, join


path1="E:\\Joseph\\360-frames"
path2="D:\\Joseph\\360-frames"
vid1 = [join(path1, f) for f in listdir(path1) if isfile(join(path1, f))]
vid2 = [join(path2, f) for f in listdir(path2) if isfile(join(path2, f))]

vid1 = sorted(vid1)
vid2 = sorted(vid2)

vid1.extend(vid2)


with open("ffmpeg_input_file.txt", "w") as f:
    for v in vid1:
        v=v.replace('\\', '/')
        f.write(f"file '{v}'\n")
        f.write(f"duration 0.033333333333\n")


'''
# ffmpeg_input_file.txt  generated by python script CyprusVitalSigns\create_ffmpeg_file.py
ffmpeg -r 30  -f concat -safe 0  -i "CyprusVitalSigns\CyprusVitalSigns\\ffmpeg_input_file.txt"  -c:v libx265 -preset slow -crf 17 -vf "scale=8192x8192" -pix_fmt yuv420p -an -movflags faststart -r 30 "Blender\VR\\test9.mp4"

ffmpeg -i "Blender\VR\test9.mp4" -i "Blender\VR\\audio_v7.flac" -map 0:v -map 1:a -c:v copy -shortest test9_with_audio_v7.mp4
'''

