sudo apt install blender
sudo apt install ffmpeg
mkdir code
cd code
git clone https://github.com/hovjdev/CyprusVitalSigns.git
python3 -m venv env
source env/bin/activate
cd CyprusVitalSigns
pip install -r requirements.txt



# dont forget to create a .env file
# VIMEO_TOKEN=...
# VIMEO_ID=...
# VIMEO_SECRETS=...
# VIMEO_TOKEN=...
# VIMEO_ID=...
# VIMEO_SECRETS=...
# WEATHER_API_KEY=...